### ISSUE TITLE
Old metrics

### ISSUE THREAD

**Issue by ritik-malik** [chaoss/wg-risk#125]
This issue is to address the PR #124 ,

The number of metrics in the [metrics](https://github.com/chaoss/wg-risk/tree/master/metrics) folder and the number of metrics finalized in the [focus-areas](https://github.com/chaoss/wg-risk/tree/master/focus-areas) are unequal.
The [metrics](https://github.com/chaoss/wg-risk/tree/master/metrics) directory contains 2 additions metrics: 
1. [OSI Approved Licenses](https://github.com/chaoss/wg-risk/blob/master/metrics/OSI_Approved_Licenses.md)
2. [SPDX Document](https://github.com/chaoss/wg-risk/blob/master/metrics/SPDX_Document.md)

I've added all the metrics in the their respective focus-areas,
and since this `metrics` directory need to be removed according to the guidelines, where should I place these additional metrics?

**Comment by GeorgLink** [comment]
Thanks for bringing this up during the Risk WG call today.

These two metrics are part of the [Licensing](https://chaoss.community/metrics/#user-content-focus-area---licensing) focus area. Can you please move them there?

If in doubt, the [Metrics Website](https://chaoss.community/metrics/#user-content-risk) is the authoritative source of which focus area metrics should be in, because that's what they have been released as.

**Comment by ritik-malik** [comment]
Thanks for the reply @GeorgLink,
I'll do the suggested changes

**Comment by GeorgLink** [comment]
This is addressed in #124

**Comment by ritik-malik** [comment]
I think we can close this issue now,
#124 resolved this
