### ISSUE TITLE
Release Candidate Comments (Committers)

### ISSUE THREAD

**Issue by germonprez** [chaoss/wg-risk#73]
This issue was created to collect comments about the upcoming metrics release.

**This thread is for comments about Committers**

GitHub location: https://github.com/chaoss/wg-risk/blob/master/metrics/Committers.md

See all release candidates of metrics are at:
https://chaoss.community/metrics-202001/

**Comment by bproffitt** [comment]
In paragraph 1 of "Description," "This is distinct from the more broadly construed "Contributors" CHAOSS metric.." Contributors should be linked to https://github.com/chaoss/wg-common/blob/master/focus-areas/who/contributors.md

** Known Confounds **
This should be a level-3 header, and maybe another word could be used? Confounds is not a commonly used term.

"Provides" in the last paragraph is misspelled.

**Comment by sgoggins** [comment]
@bproffitt : Take a look at the edits. I addressed each of your points. I think adding the link is helpful. @klumb and @germonprez may or may not like there being a link. IMHO its not something that is going to be common in the metrics definitions, but in this case, since we are explicitly distinguishing between this metric and another one (committers) I think the link adds usability to the definition and should be in there as you suggest.

**Comment by bproffitt** [comment]
Looks good to me!

**Comment by klumb** [comment]
@sgoggins, I can't speak for @germonprez, but I like the link.

**Comment by kestewart** [comment]
"known confound" is a bit awkward.

Suggest also removing modeling information, and add illustration of it in use.

**Comment by klumb** [comment]
Did PR #86 resolve all comments?

Is this metric ready for release?

**Comment by sgoggins** [comment]
Yes.  This metric is ready for release, @klumb

**Comment by klumb** [comment]
I am marking this metric as ready for release and closing. Please reopen if that is not the case.
