### ISSUE TITLE
Bill of materials metric 

### ISSUE THREAD

**Issue by klumb** [chaoss/wg-risk#87]
@sgoggins @germonprez 

This metric was part of the previous release but is not part of the current release. It wasn't on the spreadsheet.

https://github.com/chaoss/wg-risk/blob/master/metrics/Software_Bill_of_Materials.md

It seems to be similar to the SPDX metric that is in progress for future releases.

Are we rolling this back? It didn't go through the second review period but did make it through the first so I think we could just publish the previous version but someone will need to check to make sure the template is correct.

**Comment by GeorgLink** [comment]
I seem to remember that the metric was depreciated in favor of the more precise SPDX metric.

**Comment by klumb** [comment]
I don't currently have it as part of the release. 
If it is depreciated, we need to add a comment to the release notes.

**Comment by sgoggins** [comment]
A replacement metric has been put here: https://github.com/chaoss/wg-risk/blob/master/metrics/SPDX_Document.md 

The following message was sent to the mailing list

---
Hi All, 

During the weekly call today we discussed removing the Software Bill of Materials metric from the 2020-1 release to be published on January 31, 2020. The discussion noted that the removal of this metric is for sound reasons, but to not flow through the same review process as approval of metrics. Our consensus is that we generally do not prefer to “unrelease” metrics, but we are ok with it in this case if the replacement metric is not approved. 

With that setup, here is the late breaking replacement metric for review: https://github.com/chaoss/wg-risk/blob/master/metrics/SPDX_Document.md 

The metric it replaces, software bill of materials, is here: https://github.com/chaoss/wg-risk/blob/master/metrics/Software_Bill_of_Materials.md

If you have comments on this exchange, please share them on the list, or in the related issue, here: https://github.com/chaoss/wg-risk/issues/87

Thanks!

Sean

**Comment by GeorgLink** [comment]
Thanks @sgoggins for moving this forward. 
I am okay with including the metric in the release.

1. The **Filters** section does not include filters to be used on the metric but instead is an example of someone using a specific tool (covered again in next section) and shows the example output. This content needs to either move somewhere else or, more likely, the section needs to be removed.

2. "SBOM" should probably be exploded into it's actual name "Software Bill of Materials" to avoid ambiguity.

3.  Under "Tools Providing the Metric" I am not sure how the last three items fit: Packages, Package_Files, files. Are these tools?

4. The section "Tools Providing the Metric" section is one level too high but should be changed to be a subsection of "Implementation"

5.  The figure is out of context and not explained anywhere. It might be correct, but I don't know if anyone looking at the metric will immediately see its value.  Because we are striving towards simplicity and removing content from metrics in this release, maybe the easiest edit could be to remove the figure.

**Comment by germonprez** [comment]
For the new metric. 

1) Under Tools Providing the Metric, the following don't make sense to me: 

Packages

Package_Files

Files (which may be, but are unlikely to be also included in other packages). License information is included as part of an SBOM, but the complexity of license identification is clarified in the License_Count, License_Coverage, and License_Declared metrics. 

2) Under the same heading, what is the utility of the schema? 

3) Under Filters, should you give a brief description that "from the SPDX document specific in formation, like package licenses, can be filtered out."

**Comment by GeorgLink** [comment]
With CHAOSScon and the release tomorrow, I don't think we can get this metric in. As with several other metric ideas, happy to include it in the next release.

**Comment by germonprez** [comment]
@sgoggins what is the state of affairs on this metric?

**Comment by sgoggins** [comment]
@klumb : This metric is one that we released last summer, and it is not clear to me why it was ever "unreleased" ... @germonprez @GeorgLink

**Comment by klumb** [comment]
There is some confusion around this metric. My understanding was that the SPDX metric was replacing this metric. Considerable work was done to edit the SPDX metric and it looks like it is ready for review. Unfortunately, the SPDX metric was missed in this last release so it hasn't been through any comment period.  To resolve this issue I have marked the SPDX as under review on the tracking sheet. 

https://docs.google.com/spreadsheets/d/1tAGzUiZ9jdORKCnoDQJkOU8tQsZDCZVjcWqXYOSAFmE/edit#gid=605223194

Further, I am adding the SPDX metric to the website as a CC Metric and creating a review period issue for it. It will be officially released on 2021-02
